name: test work
run-name: test runs name
on: [ push ]

jobs:
  test-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: user build
        uses: ./.github/go-micro-service-build-and-test
        with:
          service: 'users'