name: test work
run-name: test runs name
on: [ push ]

jobs:
  test-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: input
        run: echo $RUNDOM >> 1.txt
      - name: output
        run: cat 1.txt